<script type="text/javascript" async
  src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML">
</script>
<script type="text/javascript" src="http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML"></script>
<script type="text/x-mathjax-config"> MathJax.Hub.Config({ tex2jax: {inlineMath: [['$', '$']]}, messageStyle: "none" });</script>

# Visione Artificiale

## Python

### Introduzione a Python
- **Linguaggio di programmazione di alto livello**: General-purpose, progettato per favorire la leggibilità del codice.
- **Sintassi concisa**: Permette di esprimere concetti con meno linee di codice rispetto a linguaggi come C++ o Java.
- **Paradigmi di programmazione**: Supporta programmazione orientata agli oggetti, imperativa e funzionale.
- **Libreria standard**: Ampia e facilmente estendibile.
- **Open source**: Disponibile su molteplici piattaforme (Windows, Linux, Raspberry, ...).

### Storia e Versioni
- **Ideato da**: Guido van Rossum nel 1989, ispirato dai Monty Python.
- **Versioni principali**:
  - **Python 1.0** (1994): Introduzione di costrutti per la programmazione funzionale (lambda, map, filter, reduce).
  - **Python 2.0** (2000): Nuove caratteristiche come list comprehension e garbage collector.
  - **Python 3.0** (2008): Revisione non completamente compatibile con le versioni precedenti.
- **Versione utilizzata**: Esempi sviluppati con Python 3.7.

### Visione Artificiale e Python
- **Diffusione**: Utilizzato in vari settori, in particolare nell'intelligenza artificiale e visione artificiale.
- **Vantaggi**:
  - Facile da imparare.
  - Codice leggibile.
  - Librerie pronte per elaborazione immagini, gestione dati, generazione grafici.
  - Moduli numerici efficienti (scritti in C/C++).
  - Gratuito e open source.
  - Ambienti di sviluppo come Jupyter Notebooks.

### Sintassi
- **Indentazione**: Definisce i blocchi di codice.
- **Commenti**: Iniziano con `#`.
- **Istruzioni su più linee**: Usare `\` per continuare su una nuova linea.
- **Esempio**:
  ```python
    # Non si può cambiare indentazione in un blocco
    print("Salve Cesena!")
        print("Salve di nuovo!") # Errore

    if 42 < 0:
    print("Prova") # Errore
    
    # L'indentazione definisce i blocchi di codice
    if 42 < 0:
        print("Mai stampato 1")
        print("Mai stampato 2")
    print("Stampato")

    istruzione_molto_lunga = 3 + 5 + 6 + 7 + 8 \
                                + 9 + 11 + 13
    
    altra_istruzione_molto_lunga = [1, 2, 3, 4,
                                    5, 6, 7, 8,
                                    9,10,11,12]
    
    # Più istruzioni su una singola linea
    print("Possibile...") ; print("ma sconsigliato")
  ```

### Variabili
- **Creazione**: Al momento dell'inizializzazione.
- **Nomi**: Case-sensitive, iniziano con lettera o underscore.
- **Esempio**:
  ```python
    x = 42
    y = "Visione Artificiale"
    print(x, y)

    # Assegnamento dello stesso valore a più variabili
    x = y = z = 99
    print(x, y, z)

    # Assegnamento di più variabili in una linea
    x, y, z = "Rosso", "Verde", "Blu"
    print(x, y, z)

    a = "divertente" # Variabile globale

    def funzione():
        a = "facile" # Variabile locale assaestante
        print("Python è " + a)
    
    def funzione2():
        print("Python è " + a) # Variabile globale
        global a = "facile" # Sovrascrivo la globale
        print("Python è " + a)

    funzione()
    print("Python è " + a)
  ```

### Tipi di Dati
- **Tipi predefiniti**: `str`, `int`, `float`, `complex`, `list`, `tuple`, `dict`, `set`, `bool`, `bytes`.
- **Esempio**:
  ```python
  x = "Visione Artificiale"  # str
  print(type(x))  # <class 'str'>
  ```

### Oggetti, Valori e Tipi
- **Oggetti**: Ogni dato è un oggetto con tipo, identità e valore.
- **Mutabilità**: Oggetti mutabili (liste, dizionari) e immutabili (numeri, stringhe, tuple).
- **Esempio**:
  ```python
  lista = [1, 2, 3]  # mutabile
  tupla = (1, 2, 3)  # immutabile
  ```

### Operatori
- **Aritmetici**: `+`, `-`, `*`, `/`, `%`, `**`, `//`.
- **Esempio**:
  ```python
  a = 10
  b = 3
  print(a + b)  # 13
  print(a // b)  # 3
  ```

### Condizioni
- **if..elif..else**: Esecuzione condizionale.
- **Esempio**:
  ```python
  a = 10
  if a > 5:
      print("Maggiore di 5")
  elif a == 5:
      print("Uguale a 5")
  else:
      print("Minore di 5")
  ```

### Cicli
- **while**: Esecuzione finché la condizione è vera.
- **for**: Iterazione su una sequenza.
- **Esempio**:
  ```python
  for i in range(5):
      print(i)  # Stampa da 0 a 4
  ```

### Liste
- **Collezioni ordinate e modificabili**.
- **Esempio**:
  ```python
  colori = ['Rosso', 'Verde', 'Blu']
  colori.append('Giallo')
  print(colori)  # ['Rosso', 'Verde', 'Blu', 'Giallo']
  ```

### Tuple
- **Collezioni ordinate e non modificabili**.
- **Esempio**:
  ```python
  colori = ('Rosso', 'Verde', 'Blu')
  print(colori[0])  # 'Rosso'
  ```

### Insiemi
- **Collezioni non ordinate e senza duplicati**.
- **Esempio**:
  ```python
  colori = {'Rosso', 'Verde', 'Blu'}
  colori.add('Giallo')
  print(colori)  # {'Rosso', 'Verde', 'Blu', 'Giallo'}
  ```

### Dizionari
- **Collezioni di coppie chiave=valore**.
- **Esempio**:
  ```python
  studenti = {101: "C.Rossi", 102: "M.Bianchi"}
  print(studenti[101])  # "C.Rossi"
  ```

### Funzioni
- **Definizione di una funzione**  
  - Si usa la parola chiave `def` seguita da una o più righe di codice (l'indentazione è fondamentale).
  - La prima stringa (se presente) funge da documentazione (docstring).  
- **Chiamata di una funzione**  
  - Si invoca scrivendo il nome della funzione seguito da parentesi tonde, anche con eventuali argomenti.
- **Passaggio dei parametri**  
  - I parametri sono riferimenti agli oggetti.
  - Per oggetti immutabili (es. numeri, stringhe) il passaggio è simile al passaggio per valore.
  - Per oggetti mutabili (es. liste) la funzione può modificare il contenuto dell'oggetto.

**Esempio**:
```python
# Definizione della funzione senza parametri
def stampa_messaggio():
    # Docstring opzionale
    print("Addio, e grazie per tutto il pesce!")

# Chiamata della funzione
stampa_messaggio()

# Funzione con parametri e docstring
def calcola(x, y):
    """Questa è la docstring di calcola: restituisce il prodotto di x e y."""
    return x * y

print(f"Il risultato è {calcola(6, 7)}.")

# Funzione che sostituisce elementi di una lista
def sostituisci(lista, x, y):
    for (indice, valore) in enumerate(lista):
        if valore == x:
            lista[indice] = y

# Versione più "pythonic" della stessa funzione
def sostituisci2(lista, x, y):
    lista[:] = [y if v == x else v for v in lista]

l = [1, 2, 3, 1, 2, 3]
sostituisci(l, 2, 0)
sostituisci2(l, 3, -1)
print(l)
```

### Parametri delle funzioni
- **Valori di default**  
  - È possibile specificare valori predefiniti per uno o più parametri (tipicamente gli ultimi), che possono essere omessi al momento della chiamata.
- **Passaggio nominale (<nome>=<valore>)**  
  - I parametri possono essere specificati in qualsiasi ordine durante la chiamata.
- **Parametri variabili**  
  - `*args` raccoglie gli argomenti extra in una tupla.
  - `**kwargs` raccoglie gli argomenti extra nominativi in un dizionario.
  - Possono essere usati singolarmente o insieme.

**Esempio**:
```python
def calcola(x, y, z=1, k=0):
    return (x * y) / z + k

print(calcola(2, 3), calcola(2, 3, 3), calcola(2, 3, 3, -2))
print(calcola(y=1, x=3), calcola(2, 3, k=2), calcola(k=1, x=2, y=3, z=1))

def prodotto(x, *altri_fattori):
    p = x
    for f in altri_fattori:
        p *= f
    return p

print(prodotto(2), prodotto(6, 7), prodotto(2, 2, 2, 2, 2))

def Esame(corso, *argomenti, **studenti):
    print("Corso:", corso)
    print("Argomenti:", end=' ')
    for a in argomenti:
        print(a, end=', ')
    print("\nStudenti:")
    for mat in studenti:
        print(mat, studenti[mat])

Esame("Visione Artificiale", "Python", "NumPy", "OpenCV",
      M101="C.Rossi", M103="M.Bianchi", M111="L.Verdi")
```

### Unpacking
- **Unpacking nel passaggio dei parametri**  
  - L'operatore `*` permette di passare una sequenza (lista, tupla, ecc.) come singoli argomenti a una funzione.
  - L'operatore `**` permette di passare un dizionario come argomenti nominativi.
- **Unpacking nell'assegnamento**  
  - Consente assegnamenti multipli in una sola riga.
  - L'operatore `*` permette di catturare tutti gli elementi restanti in una lista.

**Esempio**:
```python
def calcola(a, b, c):
    return a + b + c

parametri = [4, 18, 20]
print(calcola(*parametri))  # Unpacking della lista

a = ["Python", "NumPy", "OpenCV"]
s = {"M101": "C.Rossi", "M103": "M.Bianchi", "M111": "L.Verdi"}
Esame("Visione Artificiale", *a, **s)

# Unpacking nell'assegnamento
x, y, z = [2, 3, 4]  # Equivale a (x, y, z) = (2, 3, 4)
a1, a2, a3 = a # a1,a2,a3 vengono inizializzate dagli elementi di a
print(a1, a2, a3)

a1, *r = a # a1 viene inizializzato dal primo elemento di a r diverra un alista con il resto degli elementi
print(a1, r)

primo, secondo, *altri, ultimo = range(10)
print(primo, secondo, ultimo, altri)
```

### Funzioni come oggetti e lambda
- **Funzioni come oggetti**  
  - In Python, le funzioni sono oggetti: hanno un tipo, possono avere attributi, essere assegnate a variabili, immagazzinate in strutture dati e passate come argomenti ad altre funzioni.
- **Funzioni anonime (lambda)**  
  - Le lambda sono funzioni anonime definite con la keyword `lambda` e consistono in una singola espressione.

**Esempio**:
```python
def prodotto(x, y):
    """Restituisce il prodotto di x e y."""
    return x * y

print(type(prodotto))       # <class 'function'>
print(prodotto.__name__)    # 'prodotto'
print(prodotto.__doc__)     # 'Restituisce il prodotto di x e y.'

def esegui(f, x, y):
    """Esegue la funzione f su x e y."""
    return f(x, y)

print(esegui(prodotto, 2, 3))  # 6

# Funzione lambda per calcolare la potenza
f = lambda x, y: x ** y
print(type(f))         # <class 'function'>
print(f.__name__)      # '<lambda>'
print(f.__doc__)       # None
print(esegui(f, 4, 2))  # 16

# Uso diretto di una lambda nella chiamata
print(esegui(lambda x, y: x // y, 9, 2))  # 4
```

### Alcune funzioni predefinite
- **Descrizione**:  
  L'interprete fornisce funzioni sempre disponibili, come ad esempio:  
  - `print()`, `type()`, `id()`, `bool()`, `int()`, `float()`, `str()`, `range()`, `list()`, `tuple()`, `set()`, `dict()`, `len()`
- **Altri esempi utili**:  
  - `enumerate()`: consente di iterare su una sequenza ottenendo coppie (indice, valore).
  - `zip()`: aggrega più sequenze in una sequenza di tuple.
  - `sum()`, `min()`, `max()`: restituiscono rispettivamente la somma, il minimo e il massimo dei valori di una sequenza.
  - `sorted()`: restituisce una sequenza in ordine.

**Esempio**:
```python
s = "Python"
a = list(enumerate(s))
print(a)
# Output: [(0, 'P'), (1, 'y'), (2, 't'), (3, 'h'), (4, 'o'), (5, 'n')]

n = [ord(c) for c in s]
print(n, sum(n), min(n), max(n))
# Output: [80, 121, 116, 104, 111, 110] 642 80 121

print(sorted(n))
# Output: [80, 104, 110, 111, 116, 121]

z = list(zip(s, n))
print(z)
# Output: [('P', 80), ('y', 121), ('t', 116), ('h', 104), ('o', 111), ('n', 110)]
```

### Moduli
- **File Python**: Contengono definizioni e istruzioni.
- **Esempio di importazione**:
  ```python
  # Modulo fib.py
  def fibonacci(n): # serie di Fibonacci fino a n
  result = []
  a, b = 0, 1
  while a < n:
  result.append(a)
  a, b = b, a+b
  return result

  # Esempi di importazione
  import fib
  print(fib.fibonacci(90))

  import fib as f
  print(f.fibonacci(90))

  from fib import fibonacci
  print(fibonacci(90))
  ```

### Interprete
- **Esecuzione**: Necessario installare un interprete Python.
- **Modalità**: Interattiva o per eseguire file `.py`.
```

## NumPy

- **Descrizione**: NumPy (Numerical Python) è un pacchetto fondamentale per il calcolo scientifico in Python.
  - Consente di lavorare in modo efficiente su grandi quantità di dati memorizzati come vettori e matrici.
- **Python fornisce**:
  - Oggetti numerici di alto livello (int, float, …).
  - Comode strutture dati: tuple, liste, dizionari.
- **Limitazione**: Gestire grossi moli di dati direttamente in Python risulterebbe poco efficiente.
- **Arricchimenti di NumPy**:
  - Un array multi-dimensionale efficiente e con potenti funzionalità.
  - Sofisticate tecniche per operare su tale struttura dati.
  - Utili funzioni matematiche di base (algebra lineare, FFT, numeri random, …).

### Vantaggi di NumPy
- **Efficienza**: Funzioni e operatori agiscono su interi vettori, riducendo la necessità di loop espliciti, tipicamente poco efficienti.
- **Accesso agli elementi**: Simile alle liste in Python (utilizzo di parentesi quadre e slicing).
- **Ottimizzazione**: Codice scritto in C e altamente ottimizzato.
- **Prestazioni**: Algoritmi ben testati progettati per fornire buone prestazioni.
- **Tipi omogenei**: Gli array contengono elementi tutti dello stesso tipo (es. tutti interi a 32 bit) memorizzati in modo contiguo, approccio meno flessibile ma più efficiente.
- **Velocità di I/O**: Le operazioni di I/O di array sono significativamente più veloci.

### NumPy e OpenCV
- **Integrazione**: OpenCV-Python utilizza NumPy per memorizzare e operare sulla maggior parte dei dati.
- **Rappresentazione delle immagini**: Le immagini con più canali sono rappresentate come array tridimensionali, facilitando l'accesso ai pixel (indexing, slicing, …).
- **Strutture dati**: Altre strutture utilizzate in OpenCV (es. filtri, matrici di trasformazione, vettori di caratteristiche) sono array NumPy, semplificando lo sviluppo del codice e l'interazione con altri pacchetti software basati su NumPy.

### Utilizzare NumPy
- **Installazione**:
  - Il modulo NumPy è incluso nelle principali distribuzioni di software scientifico Python (es. Anaconda).
  - Maggiori informazioni sul sito ufficiale: [https://numpy.org](https://numpy.org).
- **Importazione**:
  - Importare il modulo NumPy è semplice; è consuetudine farlo con il nome locale `np`.
```python
import numpy as np
print(np.__version__)
```

### La classe ndarray
- **Descrizione**: La classe principale in NumPy; tutti gli array NumPy sono oggetti di questo tipo.
- **Caratteristiche**:
  - Implementa un array multidimensionale omogeneo (tutti gli elementi hanno lo stesso tipo, di solito numerico).
- **Attributi importanti**:
  - `ndim`: Numero di dimensioni (assi).
  - `shape`: Tupla di interi che indica il numero di elementi lungo ciascuna dimensione.
  - `size`: Numero totale di elementi dell'array.
  - `dtype`: Tipo degli elementi.
  - `itemsize`: Dimensione (in byte) di ogni elemento.
  - `data`: Buffer contenente gli elementi (normalmente non serve: si accede agli elementi con le parentesi quadre).

### Esempio di array
```python
a = np.array([[0, 1, 1, 2, 3],
              [5, 8, 13, 21, 34],
              [55, 89, 144, 233, 377]])
print('type:', type(a))
print('ndim:', a.ndim)
print('shape:', a.shape)
print('size:', a.size)
print('dtype:', a.dtype)
print('itemsize:', a.itemsize)
```
- **Output**:
```
type: <class 'numpy.ndarray'>
ndim: 2
shape: (3, 5)
size: 15
dtype: int32
itemsize: 4
```

### Creare un array: la funzione array()
- **Descrizione**: La funzione `array` consente di creare un array partendo da una lista o tupla Python. Il tipo dell'array viene dedotto dagli elementi, oppure può essere specificato.
```python
a = np.array([2, 3, 5])
print(a.ndim, a.shape, a.dtype, a.itemsize)

a = np.array([2, 3, 5], np.uint8)
print(a.ndim, a.shape, a.dtype, a.itemsize)

# Sequenze di sequenze sono trasformate in array bidimensionali
a = np.array([[0, 1, 1, 2, 3],
              [5, 8, 13, 21, 34],
              [55, 89, 144, 233, 377]])
print(a.ndim, a.shape, a.dtype, a.itemsize)

a = np.array([[[1, 2]], [[3, 4]]])
print(a.ndim, a.shape, a.dtype, a.itemsize)
```
- **Output**:
```
1 (3,) int32 4
1 (3,) uint8 1
2 (3, 5) int32 4
3 (2, 1, 2) int32 4
```

### Altri modi per creare un array
- **empty()**: Crea un array lasciando i valori non inizializzati.
```python
a = np.empty((2, 7), np.int16)  # 2 righe, 7 colonne
print(a)
```
- **zeros() e ones()**: Creano array di zeri o uno.
```python
print(np.zeros(5))          # Array di zeri
print(np.ones(3, np.int))   # Array di uno
print(np.zeros((2, 3)))     # Array 2x3 di zeri
```
- **arange()**: Simile a `range()` di Python.
```python
a = np.arange(100, 110, 2)
print(a)  # [100 102 104 106 108]
```
- **identity()**: Crea una matrice identità.
```python
a = np.identity(3)
print(a)
# Output:
# [[1. 0. 0.]
#  [0. 1. 0.]
#  [0. 0. 1.]]
```

### Tipi di dati numerici
- **Descrizione**: NumPy supporta una varietà di tipi numerici primitivi, maggiore rispetto a Python (interi a 8/16/32/64 bit, float a 32/64 bit, …).
- **Nota**: Non esiste un tipo primitivo NumPy che corrisponde al tipo `int` di Python (che non ha limiti di lunghezza).

| Tipo NumPy   | Equivalente C      | Note                          |
|--------------|-----------------------|------------------------------|
| np.byte      | signed char         | Dipendente dalla piattaforma   |
| np.ubyte     | unsigned char       | Dipendente dalla piattaforma   |
| np.short     | signed short        | Dipendente dalla piattaforma   |
| np.ushort    | unsigned short      | Dipendente dalla piattaforma   |
| np.intc      | signed int          | Dipendente dalla piattaforma   |
| np.uintc     | unsigned int        | Dipendente dalla piattaforma   |
| np.int_      | signed long         | Dipendente dalla piattaforma   |
| np.uint      | unsigned long       | Dipendente dalla piattaforma   |
| np.longlong  | long long           | Dipendente dalla piattaforma   |
| np.ulonglong | unsigned long long  | Dipendente dalla piattaforma   |
| np.half      | Float a 16 bit      | (mezza precisione)            |
| np.single    | float               | Singola precisione            |
| np.double    | double              | Doppia precisione             |
| np.longdouble| long double         | Precisione estesa             |
| np.csingle   | single complex      | Num. complesso prec. singola  |
| np.cdouble   | double complex      | Num. complesso prec. doppia    |
| np.clongdouble| long double complex | Num. complesso prec. estesa    |

### Tipi di dati numerici (alias a dimensione fissa)
- **Descrizione**: Molti dei tipi numerici primitivi NumPy dipendono dalla piattaforma, ad esempio `np.int_` può essere a 32 bit su Windows e a 64 bit su altre piattaforme.
- **Alias**: Sono disponibili alias per i tipi NumPy che hanno un numero di bit prefissato e indipendente dalla piattaforma.
- **Utilizzo di tipi Python**: È possibile utilizzare tipi Python per indicare tipi NumPy.
  
| Tipo NumPy   | Equivalente C      | Note                          |
|--------------|---------------------|----------------------------|
| np.int8      | int8_t              | 1 byte [-128, 127]           |
| np.uint8     | uint8_t             | 1 byte [0, 255]              |
| np.int16     | int16_t             | 2 byte [-32768, 32767]       |
| np.uint16    | uint16_t            | 2 byte [0, 65535]            |
| np.int32     | int32_t             | 4 byte [-2147483648, 2147483647] |
| np.uint32    | uint32_t            | 4 byte [0, 4294967295]       |
| np.int64     | int64_t             | 8 byte [-9223372036854775808, 9223372036854775807] |
| np.uint64    | uint64_t            | 8 byte [0, 18446744073709551615] |
| np.float32   | float               | 4 byte                        |
| np.float64   | double              | 8 byte (corrisponde a float in Python) |
| np.complex64  | float complex      | 8 byte                        |
| np.complex128 | double complex     | 16 byte (corrisponde a complex in Python) |

### Operazioni di base
- **Descrizione**: Gli operatori aritmetici si applicano agli array elemento-per-elemento; il risultato viene tipicamente memorizzato in un nuovo array.
```python
a = np.array([25, 36, 49, 64])
b = np.arange(4)
print(b)  # Output: [0 1 2 3]
c = a - b
print(c)  # Output: [25 35 47 61]
print(b ** 2)  # Output: [0 1 4 9]
print(np.sqrt(a))  # Output: [5. 6. 7. 8.]
print(a < 37)  # Output: [ True  True False False]
b = np.array([25, 37, 49, 63])
print(a == b)  # Output: [ True False True False]
```

### Prodotto
- **Descrizione**: L'operatore prodotto `*` opera elemento-per-elemento; dall versione 3.5 di Python è disponibile l'operatore `@` per i prodotti fra matrici.
```python
A = np.array([[1, 1],
              [0, 1]])
B = np.array([[2, 0],
              [3, 4]])
print(A * B)  # Prodotto elemento-per-elemento
print(A @ B)   # Prodotto tra matrici

# Un vettore "colonna": shape = (3, 1)
c = np.array([[1], [2], [3]])
# Un vettore "riga": shape = (1, 3)
r = np.array([[3, 0, 2]])
print(c @ r)  # (3,1)x(1,3) = (3,3)
print(r @ c)  # (1,3)x(3,1) = (1,1)
```
- **Output**:
```
[[2 0]
 [0 4]]
[[5]]
```

### Operatori di assegnamento
- **Descrizione**: Gli operatori di assegnamento come `+=` o `*=` modificano l'array esistente senza doverne creare uno nuovo.
- **Esempio**:
```python
a = np.ones((2, 3))
b = np.array([[1, 0, 2], [0, 3, 0]])
id_a = id(a)
a *= b
print(a)  # Output: [[1. 0. 2.]
           #          [0. 3. 0.]]
print(id_a, id(a), id_a == id(a))  # id_a rimane lo stesso

a = a * b
print(a)  # Output: [[1. 0. 4.]
           #          [0. 9. 0.]]
print(id_a, id(a), id_a == id(a))  # id_a cambia
```

### Type cast
- **Descrizione**: NumPy supporta una varietà di tipi numerici primitivi. In un'operazione fra array di tipo diverso, il tipo del risultato corrisponde a quello più preciso (o più generale) dei due.
- **Esempio**:
```python
a = np.ones(3, np.int32)
b = np.array([1.4, 1.5, 1.6])
print(a.dtype, b.dtype)  # Output: int32 float64

c = a + b
print(c)  # Output: [2.4 2.5 2.6]
print(c.dtype)  # Output: float64

# Cambiare il tipo di un array esistente
a = np.arange(10, dtype=np.uint8)
print(a.dtype)  # Output: uint8
a = a.astype(np.uint64)
print(a.dtype)  # Output: uint64
```

### Altre operazioni su un array
- **Descrizione**: NumPy offre funzioni per operare su array, come calcolare il valore minimo, massimo e la somma.
- **Esempio**:
```python
# Crea una matrice contenente numeri casuali nell'intervallo [0,1)
a = np.random.random((2, 3))
print(a)

# Calcola il valore minimo, massimo e la somma
print(f'Min: {a.min()}')
print(f'Max: {a.max()}')
print(f'Sum: {a.sum()}')

# Calcolo lungo uno specifico asse
print(f'Somma di ogni colonna: {a.sum(axis=0)}')
print(f'Somma di ogni riga: {a.sum(axis=1)}')
```

### Funzioni universali (ufunc)
- **Descrizione**: Funzioni NumPy che operano su ndarray elemento-per-elemento. Alcune ufunc sono automaticamente chiamate quando si usano i corrispondenti operatori Python.
- **Esempi di ufunc**:
  - Operazioni matematiche: `add`, `subtract`, `multiply`, `divide`, `power`, `exp`, `log`, `sqrt`.
  - Trigonometria: `sin`, `cos`, `tan`, `arcsin`, `arccos`, `arctan`, `arctan2`, `sinh`, `cosh`, `tanh`, `deg2rad`, `rad2deg`.
  - Operazioni sui bit: `bitwise_and`, `bitwise_or`, `bitwise_xor`, `invert`, `left_shift`, `right_shift`.
  - Confronto: `greater`, `greater_equal`, `less`, `less_equal`, `not_equal`, `equal`, `logical_and`, `logical_or`, `logical_xor`, `logical_not`, `maximum`, `minimum`, `fmax`, `fmin`.
  - Floating point: `isfinite`, `isinf`, `isnan`, `fabs`, `floor`, `ceil`, `trunc`.

### Indicizzazione e slicing su array monodimensionali
- **Descrizione**: Negli array NumPy monodimensionali, l'accesso agli elementi è simile a quello delle liste e altre sequenze in Python.
- **Esempio**:
```python
a = np.arange(10)**3
print(a)  # Output: [ 0 1 8 27 64 125 216 343 512 729]
print(a[2])  # Accesso a un elemento: Output: 8
print(a[2:5])  # Slicing: dall'elemento 2 al 4: Output: [ 8 27 64]

a[:6:2] = 42  # Modifica elementi di posto 0, 2, 4
print(a)  # Output: [42 1 42 27 42 125 216 343 512 729]
print(a[::-1])  # Step negativo: ordine inverso

a[::2] += a[1::2]  # a[i] += a[i+1], i=0,2,4,6,8
print(a)  # Output: [ 43 1 69 27 167 125 559 343 1241 729]

a[:] = -1  # Modifica tutti gli elementi
print(a)  # Output: [-1 -1 -1 -1 -1 -1 -1 -1 -1 -1]
```

### Indicizzazione e slicing su array multidimensionali
- **Descrizione**: Negli array multidimensionali, l'accesso agli elementi è simile a quello delle liste e altre sequenze in Python.
- **Esempio**:
```python
a = np.fromfunction(lambda i, j: i * 10 + j, (3, 5), dtype=int)
print(a)
# Output:
# [[ 0  1  2  3  4]
#  [10 11 12 13 14]
#  [20 21 22 23 24]]

# Riga 2, Colonna 3
print(a[2, 3])  # Output: 23

# Righe 0 e 1, colonna 2
print(a[:2, 2])  # Output: [ 2 12]

# La colonna 1
print(a[:, 1])  # Output: [ 1 11 21]

# La riga 1
print(a[1, :])  # Output: [10 11 12 13 14]

# La riga 1: eventuali indici mancanti sono sostituiti con ':'
print(a[1])  # Output: [10 11 12 13 14]
```

### Slicing su array multidimensionali: altri esempi
- **Descrizione**: Lo slicing consente di selezionare porzioni di un array multidimensionale.
- **Esempio**:
```python
a = np.fromfunction(lambda i, j: i * 10 + j, (3, 5), dtype=int)
print(a)
# Output:
# [[ 0  1  2  3  4]
#  [10 11 12 13 14]
#  [20 21 22 23 24]]

# Righe 0 e 2, colonne 0 e 3
print(a[::2, ::3])  # Output: [[ 0  3]
                     #          [20 23]]

# Righe 1 e 2
print(a[1:3])  # Output: [[10 11 12 13 14]
                 #          [20 21 22 23 24]]

# Righe 0 e 1, colonne 0, 1 e 2
print(a[:2, :3])  # Output: [[ 0  1  2]
                     #          [10 11 12]]

# Ultime due righe
print(a[-2:])  # Output: [[10 11 12 13 14]
                 #          [20 21 22 23 24]]
```

### Slicing con ellissi (…)
- **Descrizione**: L'ellissi è un oggetto Python predefinito che può essere indicato con `...`. NumPy lo utilizza nello slicing per rappresentare tutti i `:` che mancano per produrre una tupla di indicizzazione completa.
- **Esempi**:
  - Se `v` è un array con 5 dimensioni:
    - `v[1, 2, ...]` equivale a `v[1, 2, :, :, :]`
    - `v[..., 3]` equivale a `v[:, :, :, :, 3]`
    - `v[4, ..., 5, :]` equivale a `v[4, :, :, 5, :]`
- **Utilizzo**: Questo è utile solo in array con tre o più dimensioni.

**Esempio**:
```python
# Inizializza un array con 3 dimensioni
c = np.array([[[0, 1, 2],
                [10, 12, 13]],
               [[50, 51, 52],
                [60, 62, 63]]])
print(c.shape)  # Output: (2, 2, 3)

print(c[1, ...])  # Equivale a c[1] e a c[1, :, :]
# Output: [[50 51 52]
#          [60 62 63]]

print(c[..., 2])  # Equivale a c[:, :, 2]
# Output: [[ 2 13]
#          [52 63]]
```

### Iterare su un array
- **Descrizione**: È possibile iterare sugli elementi di un array monodimensionale e multidimensionale in NumPy.
- **Esempio**:
```python
a = np.arange(7)
print(a)  # Output: [0 1 2 3 4 5 6]

# Iterazione su un array monodimensionale
for x in a:
    print(x, end='; ')
print()

# Creazione di un array bidimensionale
a = np.fromfunction(lambda i, j: i * 10 + j, (3, 5), dtype=int)
print(a)
# Output:
# [[ 0  1  2  3  4]
#  [10 11 12 13 14]
#  [20 21 22 23 24]]

# Iterazione su una matrice
for r in a:
    for x in r:  # Iterazione su ogni riga
        print(x, end='; ')
    print()

# Utilizzo dell'attributo .flat per iterare su tutti gli elementi
for x in a.flat:
    print(x, end=', ')
```


### Modifica della forma
- **Descrizione**: NumPy consente di modificare la forma degli array utilizzando funzioni come `reshape()` e `resize()`.
- **Esempio**:
```python
a = np.arange(12)
print(a.shape)  # Output: (12,)
print(a)        # Output: [ 0 1 2 3 4 5 6 7 8 9 10 11]

# reshape() restituisce gli stessi dati con forma diversa
b = a.reshape(2, 6)
print(b.shape)  # Output: (2, 6)
print(b)        # Output: [[ 0 1 2 3 4 5]
                 #          [ 6 7 8 9 10 11]]

# Se una dimensione è -1, viene calcolata automaticamente
c = a.reshape(2, 2, -1)
print(c.shape)  # Output: (2, 2, 3)
print(c)        # Output: [[[ 0 1 2]
                 #          [ 3 4 5]]
                 #         [[ 6 7 8]
                 #          [ 9 10 11]]]

# resize() modifica l'array stesso
a.resize(2, 6)
print(a)        # Output: [[ 0 1 2 3 4 5]
                 #          [ 6 7 8 9 10 11]]

# ravel() restituisce i dati come array monodimensionale
d = a.ravel()
print(d)        # Output: [ 0 1 2 3 4 5 6 7 8 9 10 11]
```


### Altri modi per modificare la forma
- **Descrizione**: NumPy offre diversi metodi per modificare la forma degli array, inclusa l'aggiunta di nuove dimensioni.
- **Esempio**:
```python
a = np.arange(12).reshape(2, 6)
print(a)  # Output: [[ 0 1 2 3 4 5]
            #          [ 6 7 8 9 10 11]]

# Aggiunta di nuove dimensioni con np.newaxis
b = a[np.newaxis, ...]
print(b.shape)  # Output: (1, 2, 6)
print(b)        # Output: [[[ 0 1 2 3 4 5]
                 #           [ 6 7 8 9 10 11]]]

c = a[np.newaxis, ..., np.newaxis, np.newaxis]
print(c.shape)  # Output: (1, 2, 6, 1, 1)

# np.newaxis non è altro che un riferimento a None
print(np.newaxis is None)  # Output: True

# Scambiare le dimensioni con transpose() o .T
d = a.T
e = a.transpose()
print(d.shape, e.shape)  # Output: (6, 2) (6, 2)

# squeeze() elimina eventuali dimensioni a uno
f = c.squeeze()
print(f.shape)  # Output: (2, 6)
```


### Concatenare array
- **Descrizione**: NumPy consente di concatenare array utilizzando funzioni come `vstack`, `hstack` e `column_stack`.
- **Esempio**:
```python
a = np.floor(10 * np.random.random((2, 2)))
print(a)  # Output: [[5. 6.]
            #          [2. 0.]]

b = np.floor(10 * np.random.random((2, 2)))
print(b)  # Output: [[4. 8.]
            #          [1. 7.]]

# Concatenazione verticale
print(np.vstack((a, b)))  # Output: [[5. 6.]
                             #          [2. 0.]
                             #          [4. 8.]
                             #          [1. 7.]]

# Concatenazione orizzontale
print(np.hstack((a, b)))  # Output: [[5. 6. 4. 8.]
                             #          [2. 0. 1. 7.]]

# column_stack() affianca array 1D come colonne di un array 2D
x = np.array([4., 2.])
y = np.array([3., 8.])
print(np.column_stack((x, y)))  # Output: [[4. 3.]
                                    #          [2. 8.]]

# Differenza se si usa hstack()
print(np.hstack((x, y)))  # Output: [4. 2. 3. 8.]
```
### Copie e viste di array
- **Descrizione**: In NumPy, l'assegnamento non crea un nuovo oggetto, ma solo un nuovo riferimento. Lo slicing crea una vista, un nuovo oggetto che condivide gli stessi dati.
- **Esempio**:
```python
a = np.arange(7)
print(a)  # Output: [0 1 2 3 4 5 6]

# Assegnamento di riferimento
b = a
print(b is a)  # Output: True

# Slicing crea una vista
c = a[3::2]
print(c is a, c.base is a)  # Output: False True
print(c)  # Output: [3 5]

# Modifica della vista
c[0] = -1
print(a)  # Output: [ 0  1  2 -1  4  5  6]

# Creazione di una copia
d = a.copy()  # Il metodo copy() crea una copia dell'array
print(d is a, d.base is a, d.base)  # Output: False False None
d[0] = -1
print(d, a)  # Output: [-1  1  2 -1  4  5  6] [ 0  1  2 -1  4  5  6]
```

### Broadcasting
- **Descrizione**: Comodo e potente strumento che consente alle ufunc di agire su input con forme diverse.
  - **Prima regola**: Se gli array di input non hanno lo stesso numero di dimensioni, un "1" viene anteposto alla shape dell'array più piccolo.
  - **Seconda regola**: Le dimensioni a 1 sono trattate come se il numero di elementi fosse pari a quello dell'array con più elementi lungo le corrispondenti dimensioni.
  - Se dopo l'applicazione di queste due regole gli array hanno la stessa forma, l'operazione viene eseguita.
- **Esempio**:
```python
a = np.array([7, 5, 3, 1])
print(a)  # Output: [7 5 3 1]

b = np.arange(8).reshape(2, -1)
print(b)  # Output: [[0 1 2 3]
            #          [4 5 6 7]]

# Somma con broadcasting
c = a + b
print(c)  # Output: [[ 7  6  5  4]
            #          [11 10  9  8]]

# Prodotto con broadcasting
print(b * 2)  # Output: [[ 0  2  4  6]
                #          [ 8 10 12 14]]
```

### Indicizzare con un array di indici
- **Descrizione**: Oltre a interi e slicing, si possono utilizzare array di interi per indicizzare altri array.
- **Esempio**:
```python
a = np.arange(12)**2
print(a)  # Output: [ 0  1  4  9 16 25 36 49 64 81 100 121]

# Utilizzo di un array di indici
idx1 = np.array([1, 1, 3, 8, 5])
print(a[idx1])  # Output: [ 1  1  9 64 25]

# Array di indici multidimensionale
idx2 = np.array([[3, 4], [9, 7]])
print(a[idx2])  # Output: [[ 9 16]
                  #          [81 49]]
```

### Indicizzare un array multidimensionale con array di indici
- **Descrizione**: Se l'array è multidimensionale, si può passare un array di indici per ciascuna dimensione, purché abbiano la stessa forma.
- **Esempio**:
```python
a = (np.arange(12)**2).reshape(3, 4)
print(a)  # Output: [[ 0  1  4  9]
            #          [16 25 36 49]
            #          [64 81 100 121]]

idx2 = np.array([1, 1, 2])
print(a[idx2, :])  # Output: [[16 25 36 49]
                     #          [16 25 36 49]]

print(a[:, idx2])  # Output: [[ 1  1]
                     #          [25 25]
                     #          [81 81]]

idx_r = np.array([[0, 0, 0], [1, 1, 1]])
idx_c = np.array([[2, 3, 2], [0, 0, 0]])
print(a[idx_r, idx_c])  # Output: [[ 4  9  4]
                          #          [16 16 16]]
```

### Indicizzare con array di booleani
- **Descrizione**: Nell'indicizzazione con array di interi si specificano gli indici da considerare, mentre con array booleani si scelgono esplicitamente quali elementi includere.
- **Esempio**:
```python
a = np.arange(12).reshape(3, 4)
print(a)  # Output: [[ 0  1  2  3]
            #          [ 4  5  6  7]
            #          [ 8  9 10 11]]

b = a > 4
print(b)  # Output: [[False False False False]
            #          [False  True  True  True]
            #          [ True  True  True  True]]

print(a[b])  # Output: [ 5  6  7  8  9 10 11]

# Selezione con elementi booleani
criterio = a % 3 == 0
print(criterio)  # Output: [[ True False False True]
                  #          [False False  True False]
                  #          [ True False False False]]

print(a[criterio])  # Output: [0 3 6 9]
```
